#!/system/bin/sh

touch /data/eth_status
chmod 666 /data/eth_status

while true;
do
    eth=$(cat /data/eth_status)

    if [[ $eth == "0" ]]; then
        ip link set eth0 down
        sleep 5
    elif [[ $eth == "1" ]]; then
        ip link set eth0 up
        sleep 5
    fi

    echo "" > /data/eth_status
    sleep 2
done &
